// Generated by scripts/sync-tencent-program.mjs. Do not edit manually.

export type Conference2026ProgramPerson = {
  readonly name: string;
  readonly affiliation?: string;
  readonly talkTitle?: string;
};

export type Conference2026ProgramSourceSession = {
  readonly sourceTime: string;
  readonly title: string;
  readonly chairs: readonly Conference2026ProgramPerson[];
  readonly speakers: readonly Conference2026ProgramPerson[];
};

export const conference2026ProgramSource = {
  "url": "https://docs.qq.com/sheet/DUnZzaE5Ia2pVRHRj?tab=BB08J2",
  "tabId": "BB08J2",
  "sheetName": "工作表1",
  "sourceHash": "cbaa7d45ab9981f80149b65ea583e4fd905c287bf77c12cc6806761560a63df6",
  "sessions": [
    {
      "sourceTime": "10.17上午",
      "title": "Keynote",
      "chairs": [
        {
          "name": "王健桥",
          "affiliation": "清华大学"
        }
      ],
      "speakers": [
        {
          "name": "孙茂松",
          "affiliation": "清华大学"
        },
        {
          "name": "冯建峰",
          "affiliation": "复旦大学",
          "talkTitle": "Neuroscience Where AI = Science"
        },
        {
          "name": "邱子涵",
          "affiliation": "Qwen",
          "talkTitle": "大模型中离群值的功能性分析"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "AI4Math & Theory",
      "chairs": [
        {
          "name": "刘方辉",
          "affiliation": "上海交通大学"
        }
      ],
      "speakers": [
        {
          "name": "罗涛",
          "affiliation": "上海交通大学",
          "talkTitle": "从Math4AI到AI4Math的初步探索"
        },
        {
          "name": "邹荻凡",
          "affiliation": "香港大学",
          "talkTitle": "LLM for ML Theory at Scale: The VALG Agent and OpenTheoryBench"
        },
        {
          "name": "沈皓",
          "affiliation": "中国科学院数学与系统科学研究院",
          "talkTitle": "MechGeo: Autoformalizing and Proving Euclidean Geometry in Lean 4"
        },
        {
          "name": "刘方辉",
          "affiliation": "上海交通大学",
          "talkTitle": "StatsMLlib and LeanMarathon: 从教科书到数学研究的自动形式化"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "LLM评测 & Benchmark",
      "chairs": [
        {
          "name": "张辉帅",
          "affiliation": "北京大学"
        }
      ],
      "speakers": [
        {
          "name": "潘亮铭",
          "affiliation": "北京大学",
          "talkTitle": "大模型数据归因：从行为溯源到精准干预"
        },
        {
          "name": "刘泽群",
          "affiliation": "中关村学院",
          "talkTitle": "科学大模型的数据自动化：数据整理、推理合成与定制评测"
        },
        {
          "name": "姚金哥"
        },
        {
          "name": "张辉帅",
          "affiliation": "北京大学"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "预训练算法的新进展",
      "chairs": [
        {
          "name": "谢天",
          "affiliation": "Qwen"
        }
      ],
      "speakers": [
        {
          "name": "张华清",
          "affiliation": "清华大学"
        },
        {
          "name": "胡译文",
          "affiliation": "中国人民大学",
          "talkTitle": "Controlled LLM Training on Spectral Sphere"
        },
        {
          "name": "陈焕然",
          "affiliation": "清华大学"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "AI Infra",
      "chairs": [
        {
          "name": "杨朋昆",
          "affiliation": "清华大学"
        }
      ],
      "speakers": [
        {
          "name": "张华枫",
          "affiliation": "为沃科技"
        },
        {
          "name": "丁鹏",
          "affiliation": "羽医甘蓝"
        },
        {
          "name": "张先轶",
          "affiliation": "澎峰科技",
          "talkTitle": "基于FlagOS的高性价比混合云Token工厂"
        },
        {
          "name": "吴晨玮",
          "affiliation": "华为",
          "talkTitle": "基于昇腾的AgenticRL训练技术与企业级Agent落地实践"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "AI + Finance",
      "chairs": [
        {
          "name": "祝武",
          "affiliation": "清华大学"
        }
      ],
      "speakers": [
        {
          "name": "韩佳乐",
          "affiliation": "深圳河套学院",
          "talkTitle": "From Economic Agents to Agentic Economies: A Systems Blueprint for Economic World Models"
        },
        {
          "name": "Luyao Zhang",
          "affiliation": "Duke Kunshan University",
          "talkTitle": "Who Verifies Decentralized Information? Economic Incentives, Accountability, and Trustworthy AI Across Oracle Protocols"
        },
        {
          "name": "Yuan Zhang",
          "affiliation": "上海财经大学",
          "talkTitle": "Large and Deep Factor Models"
        },
        {
          "name": "江鸿锴",
          "affiliation": "清华大学",
          "talkTitle": "Do LLMs Forecast or Remember? A Bayesian Decomposition Framework for Leakage-Sensitive Financial Forecasting Evaluation"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "扩散模型的理论基础以及推理测算法",
      "chairs": [
        {
          "name": "陆一平",
          "affiliation": "北京大学"
        },
        {
          "name": "周默",
          "affiliation": "北京大学"
        }
      ],
      "speakers": [
        {
          "name": "焦雨领",
          "affiliation": "武汉大学"
        },
        {
          "name": "周沛劼",
          "affiliation": "北京大学",
          "talkTitle": "Simulation-Free Dynamic Unbalanced Optimal Transport and One-step Inference"
        },
        {
          "name": "史作强",
          "affiliation": "清华大学",
          "talkTitle": "Weighted Laplacian Flow: A Deterministic Particle Flow with Provable Convergence"
        },
        {
          "name": "陆一平",
          "affiliation": "北京大学"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "AI + 教育",
      "chairs": [
        {
          "name": "陈思明",
          "affiliation": "复旦大学"
        }
      ],
      "speakers": [
        {
          "name": "陈晴",
          "affiliation": "同济大学"
        },
        {
          "name": "涂尚卿",
          "affiliation": "清华大学",
          "talkTitle": "CogEvol：面向教育普惠的课件生成模型"
        },
        {
          "name": "黄沛",
          "affiliation": "华栖云教育"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "AI4Science",
      "chairs": [
        {
          "name": "田润泽",
          "affiliation": "中国人民大学"
        },
        {
          "name": "谢超",
          "affiliation": "清华大学"
        }
      ],
      "speakers": [
        {
          "name": "许慧楠",
          "affiliation": "中国科学院大学",
          "talkTitle": "Memory Mechanisms in Genomic Foundation Models"
        },
        {
          "name": "吴泰霖",
          "affiliation": "西湖大学"
        },
        {
          "name": "谢超",
          "affiliation": "清华大学"
        },
        {
          "name": "李秋熠",
          "affiliation": "中关村学院",
          "talkTitle": "基因组大模型Carbon"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "机器学习理论",
      "chairs": [
        {
          "name": "马梓业",
          "affiliation": "香港城市大学"
        }
      ],
      "speakers": [
        {
          "name": "马鉴昊",
          "affiliation": "清华大学",
          "talkTitle": "步长加速梯度下降的收敛下界"
        },
        {
          "name": "赵鹏",
          "affiliation": "南京大学",
          "talkTitle": "在线学习与大模型高效推理"
        },
        {
          "name": "常恒",
          "affiliation": "Unity China",
          "talkTitle": "Learning to Build Agents: Adaptive Planning, Memory, and Harness Evolution"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "Physics of Deep Learning",
      "chairs": [
        {
          "name": "陈焕然",
          "affiliation": "清华大学"
        }
      ],
      "speakers": [
        {
          "name": "刘子寅",
          "affiliation": "MIT"
        },
        {
          "name": "刘子鸣",
          "affiliation": "清华大学",
          "talkTitle": "从AI的物理学到AI自进化"
        },
        {
          "name": "张耀宇",
          "affiliation": "上海交通大学"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "语言模型基础",
      "chairs": [
        {
          "name": "胡天阳",
          "affiliation": "香港中文大学（深圳）"
        }
      ],
      "speakers": [
        {
          "name": "刘威杨",
          "affiliation": "香港中文大学",
          "talkTitle": "Pion: A Spectrum-Preserving Optimizer via Orthogonal Equivalence Transformation"
        },
        {
          "name": "曹原",
          "affiliation": "香港大学",
          "talkTitle": "Transformers for Operator Learning with Algorithmic Insights"
        },
        {
          "name": "李根",
          "affiliation": "香港中文大学",
          "talkTitle": "ConvergeFlow: Language Flow with Provable Convergence to Token Embeddings"
        },
        {
          "name": "罗维俭",
          "affiliation": "小红书",
          "talkTitle": "超快速扩散语言模型：现状与前沿挑战"
        }
      ]
    },
    {
      "sourceTime": "10.18下午",
      "title": "AI的数理和计算基础",
      "chairs": [
        {
          "name": "周峰",
          "affiliation": "中国人民大学"
        }
      ],
      "speakers": [
        {
          "name": "周帆",
          "affiliation": "上海财经大学"
        },
        {
          "name": "马俊杰",
          "affiliation": "中国科学院数学与系统科学研究院",
          "talkTitle": "Spiked Matrix Models with Rotationally Invariant Noise: AMP Algorithms and Optimality"
        },
        {
          "name": "许洪腾",
          "affiliation": "中国人民大学",
          "talkTitle": "面向蛋白质主链生成的四元数整流匹配技术"
        },
        {
          "name": "毛小介",
          "affiliation": "清华大学",
          "talkTitle": "Active Experimentation for Counterfactual Decision Making"
        }
      ]
    },
    {
      "sourceTime": "10.18下午",
      "title": "Agent技术及应用",
      "chairs": [
        {
          "name": "从鑫",
          "affiliation": "清华大学"
        }
      ],
      "speakers": [
        {
          "name": "王宏宁",
          "affiliation": "清华大学",
          "talkTitle": "情境学习与协作发现：人工智能赋能教育教学新范式"
        },
        {
          "name": "李鹏",
          "affiliation": "清华大学",
          "talkTitle": "自然语言驱动的数学研究智能体 - AIM系统的探索与实践"
        },
        {
          "name": "闫宇坤",
          "affiliation": "启元",
          "talkTitle": "PilotDeck - 面向生产力的智能体操作系统尝试"
        },
        {
          "name": "从鑫",
          "affiliation": "清华大学",
          "talkTitle": "Benchmarking Language Models for Statistical Problem Formulation"
        }
      ]
    }
  ]
} as const satisfies {
  readonly url: string;
  readonly tabId: string;
  readonly sheetName: string;
  readonly sourceHash: string;
  readonly sessions: readonly Conference2026ProgramSourceSession[];
};

export const conference2026ProgramSessions: readonly Conference2026ProgramSourceSession[] =
  conference2026ProgramSource.sessions;
