// Generated by scripts/sync-tencent-program.mjs. Do not edit manually.

export type Conference2026ProgramPerson = {
  readonly name: string;
  readonly affiliation?: string;
};

export type Conference2026ProgramSourceSession = {
  readonly sourceTime: string;
  readonly title: string;
  readonly chair: Conference2026ProgramPerson;
  readonly speakers: readonly Conference2026ProgramPerson[];
};

export const conference2026ProgramSource = {
  "url": "https://docs.qq.com/sheet/DUnZzaE5Ia2pVRHRj?tab=BB08J2",
  "tabId": "BB08J2",
  "sheetName": "工作表1",
  "sourceHash": "01f21282adda73bacadc70d353f429a9ed9b012957296752b004550780db180e",
  "sessions": [
    {
      "sourceTime": "10.17下午",
      "title": "AI + Math & Theory",
      "chair": {
        "name": "刘方辉",
        "affiliation": "上海交通大学"
      },
      "speakers": [
        {
          "name": "罗涛",
          "affiliation": "上海交通大学"
        },
        {
          "name": "邹荻凡",
          "affiliation": "香港大学"
        },
        {
          "name": "陆一平",
          "affiliation": "北京大学"
        },
        {
          "name": "刘方辉",
          "affiliation": "上海交通大学"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "ML theory",
      "chair": {
        "name": "马梓业",
        "affiliation": "香港城市大学"
      },
      "speakers": [
        {
          "name": "马鉴昊",
          "affiliation": "清华大学"
        },
        {
          "name": "赵鹏",
          "affiliation": "南京大学"
        }
      ]
    },
    {
      "sourceTime": "10.18下午",
      "title": "AI的数理和计算基础",
      "chair": {
        "name": "周峰",
        "affiliation": "中国人民大学"
      },
      "speakers": [
        {
          "name": "马俊杰",
          "affiliation": "中国科学院数学与系统科学研究院"
        },
        {
          "name": "许洪腾",
          "affiliation": "中国人民大学"
        },
        {
          "name": "毛小介",
          "affiliation": "清华大学"
        },
        {
          "name": "周帆",
          "affiliation": "上海财经大学"
        }
      ]
    },
    {
      "sourceTime": "10.17下午",
      "title": "预训练算法的新进展",
      "chair": {
        "name": "谢天",
        "affiliation": "Qwen"
      },
      "speakers": [
        {
          "name": "张华清",
          "affiliation": "清华大学"
        },
        {
          "name": "胡译文",
          "affiliation": "中国人民大学"
        },
        {
          "name": "邱子涵",
          "affiliation": "Qwen"
        }
      ]
    },
    {
      "sourceTime": "10.18上午",
      "title": "agentic后训练",
      "chair": {
        "name": "杨新宇",
        "affiliation": "Kimi"
      },
      "speakers": []
    },
    {
      "sourceTime": "",
      "title": "AI + 教育",
      "chair": {
        "name": "陈思明",
        "affiliation": "复旦大学"
      },
      "speakers": [
        {
          "name": "陈晴",
          "affiliation": "同济大学"
        },
        {
          "name": "涂尚卿",
          "affiliation": "清华大学"
        },
        {
          "name": "黄沛",
          "affiliation": "华栖云教育"
        }
      ]
    },
    {
      "sourceTime": "",
      "title": "Agent技术及应用",
      "chair": {
        "name": "从鑫",
        "affiliation": "清华大学"
      },
      "speakers": [
        {
          "name": "王宏宁",
          "affiliation": "清华大学"
        },
        {
          "name": "李鹏",
          "affiliation": "清华大学"
        },
        {
          "name": "从鑫",
          "affiliation": "清华大学"
        }
      ]
    },
    {
      "sourceTime": "",
      "title": "LLM评测&Benchmark",
      "chair": {
        "name": "张辉帅",
        "affiliation": "北京大学"
      },
      "speakers": []
    },
    {
      "sourceTime": "",
      "title": "AI + Finance",
      "chair": {
        "name": "祝武",
        "affiliation": "清华大学"
      },
      "speakers": []
    },
    {
      "sourceTime": "",
      "title": "语言模型基础",
      "chair": {
        "name": "胡天阳",
        "affiliation": "香港中文大学（深圳）"
      },
      "speakers": [
        {
          "name": "刘威杨",
          "affiliation": "香港中文大学"
        },
        {
          "name": "曹原",
          "affiliation": "香港大学"
        },
        {
          "name": "李根",
          "affiliation": "香港中文大学"
        },
        {
          "name": "罗维俭",
          "affiliation": "小红书"
        }
      ]
    },
    {
      "sourceTime": "",
      "title": "扩散模型的理论基础以及推理测算法",
      "chair": {
        "name": "陆一平",
        "affiliation": "北京大学"
      },
      "speakers": [
        {
          "name": "焦雨领",
          "affiliation": "武汉大学"
        },
        {
          "name": "周沛劼",
          "affiliation": "北京大学"
        },
        {
          "name": "史作强",
          "affiliation": "清华大学"
        },
        {
          "name": "陆一平",
          "affiliation": "北京大学"
        }
      ]
    },
    {
      "sourceTime": "",
      "title": "AI Infra",
      "chair": {
        "name": "杨朋昆",
        "affiliation": "清华大学"
      },
      "speakers": []
    },
    {
      "sourceTime": "",
      "title": "AI4Science",
      "chair": {
        "name": "谢超",
        "affiliation": "清华大学"
      },
      "speakers": [
        {
          "name": "许慧楠",
          "affiliation": "之江实验室"
        },
        {
          "name": "谢超",
          "affiliation": "清华大学"
        }
      ]
    }
  ]
} as const satisfies {
  readonly url: string;
  readonly tabId: string;
  readonly sheetName: string;
  readonly sourceHash: string;
  readonly sessions: readonly Conference2026ProgramSourceSession[];
};

export const conference2026ProgramSessions = conference2026ProgramSource.sessions;
