// Generated by scripts/sync-poster-research.mjs. Do not edit manually.

export type PosterResearchPaper = {
  readonly id: string;
  readonly title: string;
  readonly applicantName: string;
  readonly affiliation: string;
  readonly venue: string;
  readonly href: string;
};

export const posterResearchSource = {
  "sourceHash": "2f787fc038a5eef5dbad94bd6406db4d2aa2e51210966ae20427159f1430219a",
  "status": "registration",
  "papers": [
    {
      "id": "poster-d942ebf1012f",
      "title": "CodeHacker: Automated Test Case Generation for Detecting Vulnerabilities in Competitive Programming Solutions",
      "applicantName": "尹新祥",
      "affiliation": "香港大学 / 西北工业大学",
      "venue": "ACL",
      "href": "https://aclanthology.org/2026.acl-long.108/"
    },
    {
      "id": "poster-d2bfff1a8b53",
      "title": "FormalMATH: Benchmarking Formal Mathematical Reasoning of Large Language Models",
      "applicantName": "郁昼亮",
      "affiliation": "香港中文大学",
      "venue": "EMNLP Findings",
      "href": "https://arxiv.org/abs/2505.02735"
    },
    {
      "id": "poster-ff735f051373",
      "title": "Scaling Laws for Precision in High-Dimensional Linear Regression",
      "applicantName": "张德辰",
      "affiliation": "香港大学",
      "venue": "ICML",
      "href": "https://arxiv.org/abs/2602.19241"
    },
    {
      "id": "poster-339537805502",
      "title": "Revisiting the Role of Pretrained Weights in Model Merging: On Near-Optimality within the Core Subspace",
      "applicantName": "孙文举",
      "affiliation": "北京交通大学",
      "venue": "ICML",
      "href": "https://openreview.net/forum?id=NrGCh79ANM"
    },
    {
      "id": "poster-66e1317d6834",
      "title": "Improving Memory Efficiency for Training KANs via Meta Learning",
      "applicantName": "赵张弛",
      "affiliation": "西安交通大学",
      "venue": "ICML",
      "href": "https://proceedings.mlr.press/v267/zhao25s.html"
    },
    {
      "id": "poster-beb01cdc9c2c",
      "title": "The Implicit Bias of Steepest Descent with Mini-batch Stochastic Gradient",
      "applicantName": "李继初",
      "affiliation": "中国人民大学",
      "venue": "ICML",
      "href": "https://openreview.net/forum?id=OT9cxeWbEO"
    },
    {
      "id": "poster-20d7627de19e",
      "title": "STAR: A Benchmark for Astronomical Star Fields Super-Resolution",
      "applicantName": "巫国诚",
      "affiliation": "香港中文大学(深圳)",
      "venue": "NeurIPS",
      "href": "https://arxiv.org/abs/2507.16385"
    },
    {
      "id": "poster-1fd3f2cb86d6",
      "title": "Agentic Proposing: Enhancing Large Language Model Reasoning via Compositional Skill Synthesis",
      "applicantName": "焦政博",
      "affiliation": "上海财经大学",
      "venue": "ICML",
      "href": "https://arxiv.org/abs/2602.03279"
    },
    {
      "id": "poster-5d114adf5204",
      "title": "Reflect-then-Correct: Rebalancing Task Optimization for Generalizable Meta-Reinforcement Learning via Distributional Value Error Reduction",
      "applicantName": "王敏",
      "affiliation": "中国科学院计算技术研究所",
      "venue": "ICML",
      "href": "https://openreview.net/forum?id=AJMrn5qYih"
    },
    {
      "id": "poster-23d0d4153187",
      "title": "Statistical Inference for Generative Model Comparison",
      "applicantName": "苏瀚",
      "affiliation": "清华大学",
      "venue": "TMLR",
      "href": "https://openreview.net/forum?id=PXL6SBxh0q"
    },
    {
      "id": "poster-02cffb08a0d2",
      "title": "HyMAGE: Semantic-Aware Dynamic Hypergraph Generation",
      "applicantName": "谷炳桥",
      "affiliation": "山东大学",
      "venue": "ACM SIGKDD",
      "href": "https://doi.org/10.1145/3770855.3817897"
    },
    {
      "id": "poster-c5cc3c61e490",
      "title": "Benign Overfitting in Adversarial Training for Vision Transformers",
      "applicantName": "张家铭",
      "affiliation": "中国人民大学",
      "venue": "ICML",
      "href": "https://arxiv.org/abs/2604.19724"
    },
    {
      "id": "poster-136c923ca735",
      "title": "A novel abnormal pore pressure prediction framework based on machine learning and drilling–rock mechanics parameter data",
      "applicantName": "李华洋",
      "affiliation": "北京大学",
      "venue": "Petroleum Science",
      "href": "https://doi.org/10.1016/j.petsci.2026.06.002"
    },
    {
      "id": "poster-36f1f5719cb4",
      "title": "Beyond Static Rules: Automated Discovery of Latent Vulnerabilities in Text-to-SQL",
      "applicantName": "汪汉卿",
      "affiliation": "上海财经大学",
      "venue": "ACL Findings",
      "href": "https://aclanthology.org/2026.findings-acl.842/"
    },
    {
      "id": "poster-3ab1bd2d3392",
      "title": "PASTE-D2Net: Prior-Aware Spatio-Temporal Evolution Distillation Dual-Stream Network for Medical Single-Domain Generalization",
      "applicantName": "郑昌盛",
      "affiliation": "武汉大学",
      "venue": "ACM MM",
      "href": "https://doi.org/10.1145/3767308.3836044"
    },
    {
      "id": "poster-f520da02c99f",
      "title": "Augur: Modeling Covariate Causal Associations in Time Series via Large Language Models",
      "applicantName": "崔志清",
      "affiliation": "南京信息工程大学",
      "venue": "ACL",
      "href": "https://aclanthology.org/2026.acl-long.32/"
    },
    {
      "id": "poster-b40d938f20da",
      "title": "AlphaEval: Evaluating Agents in Production",
      "applicantName": "徐秉煜",
      "affiliation": "中国科学院大学",
      "venue": "COLM",
      "href": "https://arxiv.org/abs/2604.12162"
    },
    {
      "id": "poster-ea387cedd8d5",
      "title": "IGNN-Solver: A Graph Neural Solver for Implicit Graph Neural Networks",
      "applicantName": "林筠超",
      "affiliation": "华中科技大学",
      "venue": "T-PAMI",
      "href": "https://arxiv.org/abs/2410.08524"
    },
    {
      "id": "poster-51a63928ed19",
      "title": "Gaussian Herding across Pens: An Optimal Transport Perspective on Global Gaussian Reduction for 3DGS",
      "applicantName": "王涛",
      "affiliation": "中国人民大学",
      "venue": "NeurIPS",
      "href": "https://arxiv.org/abs/2506.09534"
    },
    {
      "id": "poster-ae83c43481fb",
      "title": "MIHC: Multi-View Interpretable Hypergraph Neural Networks with Information Bottleneck for Chip Congestion Prediction",
      "applicantName": "张泽玥",
      "affiliation": "中国人民大学",
      "venue": "NeurIPS",
      "href": "https://proceedings.neurips.cc/paper_files/paper/2025/hash/7fc54f90195097ed0ee6200f1dc274d3-Abstract-Conference.html"
    },
    {
      "id": "poster-70d62481de5a",
      "title": "When Bias Pretends to Be Truth: How Spurious Correlations Undermine Hallucination Detection in LLMs",
      "applicantName": "董亦骐",
      "affiliation": "清华大学",
      "venue": "ICLR",
      "href": "https://arxiv.org/abs/2511.07318"
    },
    {
      "id": "poster-c3b39bcfdced",
      "title": "EfficientFlow: Efficient Equivariant Flow Policy Learning for Embodied AI",
      "applicantName": "梅若风",
      "affiliation": "西安交通大学",
      "venue": "AAAI",
      "href": "https://arxiv.org/abs/2512.02020"
    },
    {
      "id": "poster-0f7dd7296a17",
      "title": "AGZO: Activation-Guided Zeroth-Order Optimization for LLM Fine-Tuning",
      "applicantName": "林威",
      "affiliation": "香港中文大学",
      "venue": "ICML",
      "href": "https://arxiv.org/abs/2601.17261"
    },
    {
      "id": "poster-f1e5e20e6992",
      "title": "STrajRAG: Supervised trajectory retrieval augmented generation for next POI recommendation with travel semantics",
      "applicantName": "林中潭",
      "affiliation": "中国人民大学",
      "venue": "Information Processing & Management",
      "href": "https://www.sciencedirect.com/science/article/pii/S0306457325001761"
    },
    {
      "id": "poster-d9beb2030ac7",
      "title": "Model-Based Imaginative Planning for Embodied Agents",
      "applicantName": "宋俊儒",
      "affiliation": "上海交通大学",
      "venue": "ACL",
      "href": "https://aclanthology.org/2026.acl-long.827/"
    },
    {
      "id": "poster-ddaa41f4696e",
      "title": "Can MLLMs Understand the Deep Implication Behind Chinese Images?",
      "applicantName": "张辰皓",
      "affiliation": "华中科技大学/腾讯",
      "venue": "ACL",
      "href": "https://aclanthology.org/2025.acl-long.700/"
    },
    {
      "id": "poster-99b01821f1a9",
      "title": "Logical Phase Transitions: Understanding Collapse in LLM Logical Reasoning",
      "applicantName": "张幸朗",
      "affiliation": "华中科技大学",
      "venue": "ACL",
      "href": "https://arxiv.org/abs/2601.02902"
    },
    {
      "id": "poster-b62b851b68d6",
      "title": "Graph-GRPO: Training Graph Flow Models with Reinforcement Learning",
      "applicantName": "朱宝恒",
      "affiliation": "香港科技大学(广州)/北京邮电大学",
      "venue": "ICML",
      "href": "https://arxiv.org/abs/2603.10395"
    },
    {
      "id": "poster-0d0abb6e4c9e",
      "title": "Delineating Knowledge Boundaries for Honest Large Vision-Language Models",
      "applicantName": "宋俊儒",
      "affiliation": "山东大学",
      "venue": "ECCV",
      "href": "https://eccv.ecva.net/virtual/2026/poster/5732"
    },
    {
      "id": "poster-4c15e914b43e",
      "title": "VKG-QA: Visual Knowledge Graph-based Question Answer for Large Multimodal Models",
      "applicantName": "杜云涛",
      "affiliation": "山东大学",
      "venue": "CVPR",
      "href": "https://openaccess.thecvf.com/content/CVPR2026/html/Du_VKG-QA_Visual_Knowledge_Graph-based_Question_Answer_for_Large_Multimodal_Models_CVPR_2026_paper.html"
    },
    {
      "id": "poster-224c26c262ff",
      "title": "Contractive Anchor Resolvent Diffusion for Incomplete Multi-View Clustering",
      "applicantName": "赵桐正",
      "affiliation": "山西大学",
      "venue": "ICML",
      "href": "https://icml.cc/virtual/2026/poster/64642"
    },
    {
      "id": "poster-37dfe0e91548",
      "title": "DSN : Energy-efficient EMG signal classification method enabling real-time monitoring for edge healthcare",
      "applicantName": "孟宪喆",
      "affiliation": "华中科技大学",
      "venue": "Neural Networks",
      "href": "https://www.sciencedirect.com/science/article/pii/S0893608026007665"
    },
    {
      "id": "poster-20cc69625fe7",
      "title": "CWF: A Collaborative Writing Framework for Personalized and Reliable Popular Science Writing",
      "applicantName": "范晓煜",
      "affiliation": "华中科技大学",
      "venue": "EMNLP",
      "href": "https://arxiv.org/abs/2609.06126"
    },
    {
      "id": "poster-63e8b1777613",
      "title": "Questioning the Coverage-Length Metric in Conformal Prediction: When Shorter Intervals Are Not Better",
      "applicantName": "卢羿舟",
      "affiliation": "复旦大学",
      "venue": "ICML",
      "href": "https://arxiv.org/abs/2601.21455"
    },
    {
      "id": "poster-a7172647caf8",
      "title": "Co4ICF: Co-evolving Physics-Informed Surrogate and RL-based Pulse Optimizer for Inertial Confinement Fusion",
      "applicantName": "赵佳彤",
      "affiliation": "上海交通大学",
      "venue": "ACM SIGKDD",
      "href": "https://arxiv.org/abs/2607.10366"
    },
    {
      "id": "poster-cb82eac05270",
      "title": "Diversity-Enhanced and Classification-Aware Prompt Learning for Few-Shot Learning via Stable Diffusion",
      "applicantName": "常高钦",
      "affiliation": "西安交通大学",
      "venue": "TMLR",
      "href": "https://openreview.net/forum?id=4CfliohyqK"
    },
    {
      "id": "poster-6fb10f7bfdf9",
      "title": "CoVer: Conflict-Aware Claim Verification",
      "applicantName": "张书宁",
      "affiliation": "清华大学",
      "venue": "EMNLP",
      "href": "https://arxiv.org/abs/2609.00508"
    },
    {
      "id": "poster-56378cca5d9b",
      "title": "ScopeBench: Evaluating Cultural Norm Scope Awareness in LLMs",
      "applicantName": "赵子维",
      "affiliation": "Technical University of Munich",
      "venue": "EMNLP",
      "href": "https://ziwayzhao.github.io/assets/pdf/ScopeBench.pdf"
    },
    {
      "id": "poster-22a8ed133827",
      "title": "Meric: A Unified Framework for Multimodal Music Generation and Retrieval via Representation Space Anchoring",
      "applicantName": "王胤博",
      "affiliation": "中国人民大学",
      "venue": "ECCV",
      "href": "https://media.eventhosts.cc/Conferences/ECCV2026/pdfs/2169.pdf"
    },
    {
      "id": "poster-c2d192f2a71b",
      "title": "MoFO: Momentum-Filtered Optimizer for Mitigating Forgetting in LLM Fine-Tuning",
      "applicantName": "王森淼",
      "affiliation": "香港中文大学（深圳）",
      "venue": "TMLR",
      "href": "https://openreview.net/forum?id=T1qXIDn9my"
    },
    {
      "id": "poster-d89d4985330b",
      "title": "CSRv2: Unlocking Ultra-Sparse Embeddings",
      "applicantName": "郭立轩",
      "affiliation": "西安电子科技大学",
      "venue": "ICLR",
      "href": "https://arxiv.org/abs/2602.05735"
    },
    {
      "id": "poster-85bec19ca7b9",
      "title": "Hystar: Hypernetwork-driven Style-adaptive Retrieval via Dynamic SVD Modulation",
      "applicantName": "蔡于嘉",
      "affiliation": "西安电子科技大学",
      "venue": "ICLR",
      "href": "https://iclr.cc/virtual/2026/poster/10006957"
    }
  ]
} as const;

export const posterResearchPapers: readonly PosterResearchPaper[] = posterResearchSource.papers;
